// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.12.4
// source: pkg/proto/bot.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewNote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Body     string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *NewNote) Reset() {
	*x = NewNote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_bot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewNote) ProtoMessage() {}

func (x *NewNote) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_bot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewNote.ProtoReflect.Descriptor instead.
func (*NewNote) Descriptor() ([]byte, []int) {
	return file_pkg_proto_bot_proto_rawDescGZIP(), []int{0}
}

func (x *NewNote) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *NewNote) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type UpdNote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	IdNote   string `protobuf:"bytes,2,opt,name=id_note,json=idNote,proto3" json:"id_note,omitempty"`
	Body     string `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *UpdNote) Reset() {
	*x = UpdNote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_bot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdNote) ProtoMessage() {}

func (x *UpdNote) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_bot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdNote.ProtoReflect.Descriptor instead.
func (*UpdNote) Descriptor() ([]byte, []int) {
	return file_pkg_proto_bot_proto_rawDescGZIP(), []int{1}
}

func (x *UpdNote) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UpdNote) GetIdNote() string {
	if x != nil {
		return x.IdNote
	}
	return ""
}

func (x *UpdNote) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type DelNote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	IdNote   string `protobuf:"bytes,2,opt,name=id_note,json=idNote,proto3" json:"id_note,omitempty"`
}

func (x *DelNote) Reset() {
	*x = DelNote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_bot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelNote) ProtoMessage() {}

func (x *DelNote) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_bot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelNote.ProtoReflect.Descriptor instead.
func (*DelNote) Descriptor() ([]byte, []int) {
	return file_pkg_proto_bot_proto_rawDescGZIP(), []int{2}
}

func (x *DelNote) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *DelNote) GetIdNote() string {
	if x != nil {
		return x.IdNote
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	IdNote string `protobuf:"bytes,2,opt,name=id_note,json=idNote,proto3" json:"id_note,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_bot_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_bot_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pkg_proto_bot_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *Response) GetIdNote() string {
	if x != nil {
		return x.IdNote
	}
	return ""
}

var File_pkg_proto_bot_proto protoreflect.FileDescriptor

var file_pkg_proto_bot_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x6f, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x4e, 0x6f, 0x74, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x22, 0x53, 0x0a, 0x07, 0x55, 0x70, 0x64, 0x4e, 0x6f, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x64, 0x5f,
	0x6e, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x64, 0x4e, 0x6f,
	0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x3f, 0x0a, 0x07, 0x44, 0x65, 0x6c, 0x4e, 0x6f, 0x74,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17,
	0x0a, 0x07, 0x69, 0x64, 0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x69, 0x64, 0x4e, 0x6f, 0x74, 0x65, 0x22, 0x3b, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x69,
	0x64, 0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x64,
	0x4e, 0x6f, 0x74, 0x65, 0x32, 0x79, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0a, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74,
	0x4e, 0x6f, 0x74, 0x65, 0x12, 0x08, 0x2e, 0x4e, 0x65, 0x77, 0x4e, 0x6f, 0x74, 0x65, 0x1a, 0x09,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0a, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x12, 0x08, 0x2e, 0x55, 0x70, 0x64, 0x4e, 0x6f, 0x74,
	0x65, 0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0a,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x12, 0x08, 0x2e, 0x44, 0x65, 0x6c,
	0x4e, 0x6f, 0x74, 0x65, 0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_bot_proto_rawDescOnce sync.Once
	file_pkg_proto_bot_proto_rawDescData = file_pkg_proto_bot_proto_rawDesc
)

func file_pkg_proto_bot_proto_rawDescGZIP() []byte {
	file_pkg_proto_bot_proto_rawDescOnce.Do(func() {
		file_pkg_proto_bot_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_bot_proto_rawDescData)
	})
	return file_pkg_proto_bot_proto_rawDescData
}

var file_pkg_proto_bot_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_bot_proto_goTypes = []interface{}{
	(*NewNote)(nil),  // 0: NewNote
	(*UpdNote)(nil),  // 1: UpdNote
	(*DelNote)(nil),  // 2: DelNote
	(*Response)(nil), // 3: Response
}
var file_pkg_proto_bot_proto_depIdxs = []int32{
	0, // 0: MessageService.InsertNote:input_type -> NewNote
	1, // 1: MessageService.UpdateNote:input_type -> UpdNote
	2, // 2: MessageService.DeleteNote:input_type -> DelNote
	3, // 3: MessageService.InsertNote:output_type -> Response
	3, // 4: MessageService.UpdateNote:output_type -> Response
	3, // 5: MessageService.DeleteNote:output_type -> Response
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_bot_proto_init() }
func file_pkg_proto_bot_proto_init() {
	if File_pkg_proto_bot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_bot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewNote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_bot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdNote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_bot_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelNote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_bot_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_bot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_bot_proto_goTypes,
		DependencyIndexes: file_pkg_proto_bot_proto_depIdxs,
		MessageInfos:      file_pkg_proto_bot_proto_msgTypes,
	}.Build()
	File_pkg_proto_bot_proto = out.File
	file_pkg_proto_bot_proto_rawDesc = nil
	file_pkg_proto_bot_proto_goTypes = nil
	file_pkg_proto_bot_proto_depIdxs = nil
}
